# Starter pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



stages:

- stage: Build

  jobs:

  - job: Linux

    pool:

      vmImage: 'Ubuntu 16.04'

    steps:

    - checkout: none

    - script: echo A!



- stage: QA

  dependsOn: Build

  jobs:

  - job: L2

    pool:

      vmImage: 'Ubuntu 16.04'

    steps:

    - checkout: none

    - script: echo B!



- stage: Ring0

  dependsOn: Build

  jobs:

  - job: SU0

    condition: eq(variables['Build.SourceBranch'], 'refs/heads/releases')

    pool:

      vmImage: 'Ubuntu 16.04'

    steps:

    - checkout: none

    - script: echo C!

    

- stage: Ring1

  dependsOn:

  - QA

  - Ring0

  condition: always()

  jobs:

  - job: SU1

    pool:

      vmImage: 'Ubuntu 16.04'

    steps:

    - checkout: none

    - script: echo D!